//go:build linux
// +build linux

// Package systune 检查/应用 anyproxy 建议的 Linux 内核网络调优(sysctl)与文件句柄。
// 与 utils/help 里 -h 输出的调优清单保持一致。
package systune

import (
	"fmt"
	"os"
	"os/exec"
	"strconv"
	"strings"
	"syscall"
)

// 建议的最少文件句柄数(RLIMIT_NOFILE)。
const recommendedNofile = 65535

// ckind 比较方式。
type ckind int

const (
	eq   ckind = iota // 必须等于 want
	gte               // 建议 >= want
	lte               // 建议 <= want
	info              // 仅展示/建议(不判定达标)
)

type tunable struct {
	key  string
	want string
	kind ckind
}

// 与 utils/help 的 -h 调优清单一致。
var tunables = []tunable{
	{"fs.file-max", "1000000", gte},
	{"net.core.default_qdisc", "fq", eq},
	{"net.ipv4.tcp_congestion_control", "bbr", eq},
	{"net.core.rmem_max", "67108864", gte},
	{"net.core.wmem_max", "67108864", gte},
	{"net.core.netdev_max_backlog", "250000", gte},
	{"net.core.somaxconn", "4096", gte},
	{"net.ipv4.tcp_syncookies", "1", eq},
	{"net.ipv4.tcp_tw_reuse", "1", eq},
	{"net.ipv4.tcp_fin_timeout", "30", lte},
	{"net.ipv4.tcp_keepalive_time", "1200", info},
	{"net.ipv4.ip_local_port_range", "10000 65000", info},
	{"net.ipv4.tcp_max_syn_backlog", "8192", gte},
	{"net.ipv4.tcp_max_tw_buckets", "524288", info},
	{"net.ipv4.tcp_fastopen", "3", eq},
	{"net.ipv4.tcp_window_scaling", "1", eq},
	{"net.ipv4.tcp_rmem", "4096 131072 67108864", info},
	{"net.ipv4.tcp_wmem", "4096 65536 67108864", info},
	{"net.ipv4.tcp_mtu_probing", "1", eq},
}

func sysctlPath(key string) string {
	return "/proc/sys/" + strings.ReplaceAll(key, ".", "/")
}

// readSysctl 读一个 sysctl 值(空白规整为单空格); 读不到返回 ok=false。
func readSysctl(key string) (string, bool) {
	b, err := os.ReadFile(sysctlPath(key))
	if err != nil {
		return "", false
	}
	return strings.Join(strings.Fields(string(b)), " "), true
}

func firstInt(s string) int64 {
	f := strings.Fields(s)
	if len(f) == 0 {
		return 0
	}
	n, _ := strconv.ParseInt(f[0], 10, 64)
	return n
}

// ok 判定当前值是否达标。
func (t tunable) ok(cur string) bool {
	switch t.kind {
	case eq:
		return cur == t.want
	case gte:
		return firstInt(cur) >= firstInt(t.want)
	case lte:
		return firstInt(cur) <= firstInt(t.want)
	default: // info
		return true
	}
}

func bbrAvailable() (avail string, ok bool) {
	avail, ok = readSysctl("net.ipv4.tcp_available_congestion_control")
	return avail, ok && strings.Contains(" "+avail+" ", " bbr ")
}

// Check 读取当前系统设置并对照建议值打印报告(只读)。返回未达标项数。
func Check() int {
	fmt.Println("== anyproxy system tuning check (Linux) ==")

	warn := 0
	// 文件句柄
	var rl syscall.Rlimit
	if err := syscall.Getrlimit(syscall.RLIMIT_NOFILE, &rl); err == nil {
		if rl.Cur >= recommendedNofile {
			fmt.Printf("  [OK]   ulimit -n (RLIMIT_NOFILE) = %d\n", rl.Cur)
		} else {
			warn++
			fmt.Printf("  [WARN] ulimit -n (RLIMIT_NOFILE) = %d (recommended >= %d)\n", rl.Cur, recommendedNofile)
		}
	}
	// BBR 是否可用
	if avail, ok := bbrAvailable(); !ok {
		warn++
		fmt.Printf("  [WARN] bbr not available in kernel (available: %s); needs kernel>=4.9 or load tcp_bbr\n", avail)
	}

	for _, t := range tunables {
		cur, ok := readSysctl(t.key)
		if !ok {
			fmt.Printf("  [SKIP] %s (not present in this kernel)\n", t.key)
			continue
		}
		switch {
		case t.kind == info && cur == t.want:
			fmt.Printf("  [OK]   %s = %s\n", t.key, cur)
		case t.kind == info:
			fmt.Printf("  [INFO] %s = %s (recommended %s)\n", t.key, cur, t.want)
		case t.ok(cur):
			fmt.Printf("  [OK]   %s = %s\n", t.key, cur)
		default:
			warn++
			fmt.Printf("  [WARN] %s = %s (recommended %s)\n", t.key, cur, t.want)
		}
	}

	if warn == 0 {
		fmt.Println("All checks passed.")
	} else {
		fmt.Printf("%d item(s) below recommendation; run sudo anyproxy -check-fix to apply.\n", warn)
	}
	return warn
}

// Apply 把建议的 sysctl 写入 /etc/sysctl.d/99-anyproxy.conf 并 sysctl -p 应用(需 root)。
// 文件句柄(ulimit)不自动改(环境相关), 仅给提示。
func Apply() {
	if os.Geteuid() != 0 {
		fmt.Println("applying system tuning needs root, run: sudo anyproxy -check-fix")
		return
	}

	var b strings.Builder
	b.WriteString("# generated by anyproxy -check-fix\n")
	for _, t := range tunables {
		b.WriteString(t.key + " = " + t.want + "\n")
	}
	path := "/etc/sysctl.d/99-anyproxy.conf"
	if err := os.WriteFile(path, []byte(b.String()), 0644); err != nil {
		fmt.Printf("failed to write %s: %v\n", path, err)
		return
	}
	fmt.Printf("wrote %s\n", path)

	out, err := exec.Command("sysctl", "-p", path).CombinedOutput()
	if s := strings.TrimSpace(string(out)); s != "" {
		fmt.Println(s)
	}
	if err != nil {
		fmt.Printf("sysctl -p failed: %v (some items may be unsupported by this kernel)\n", err)
	} else {
		fmt.Println("sysctl applied.")
	}

	if avail, ok := bbrAvailable(); !ok {
		fmt.Printf("warning: bbr not available in kernel (available: %s); tcp_congestion_control=bbr will not take effect (needs kernel upgrade or load tcp_bbr)\n", avail)
	}
	fmt.Println("note: file handle limit (ulimit -n) needs separate config -- interactive login: edit /etc/security/limits.conf;")
	fmt.Println("      systemd service: set LimitNOFILE=65535 in the unit.")
}
